name: example
description: A project that showcases usage of cached_network_image
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  baseflow_plugin_template: ^2.1.2
  cached_network_image:
    path: ../
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - packages/baseflow_plugin_template/logo.png
    - packages/baseflow_plugin_template/poweredByBaseflow.png
