name: http_mock_adapter
description: A simple to use mocking package for Dio intended to be used in tests. It provides various types and methods to declaratively mock request-response communication.
version: 0.3.3-hcifork.0
homepage: https://lomsa.com
repository: https://github.com/lomsa-dev/http-mock-adapter
issue_tracker: https://github.com/lomsa-dev/http-mock-adapter/issues

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  dio:
    git:
      url: https://github.com/zoocityboy/hci.git
      path: dio
      ref: main
  http_parser: ^4.0.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.8
  fake_async: ^1.3.1
