name: retrofit_generator
description: retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
version: 4.2.0-hcifork.0
publish_to: none

homepage: https://mings.in/retrofit.dart/
repository: https://github.com/trevorwang/retrofit.dart/

environment:
  sdk: ">=2.19.0"

dependencies:
  analyzer: ">=5.0.0"
  build: ^2.4.0
  built_collection: ^5.1.1
  code_builder: ^4.5.0
  dart_style: ^2.3.1
  dio:
    git:
      url: https://github.com/zoocityboy/hci.git
      path: dio
      ref: main
  retrofit:
    git:
      url: https://github.com/zoocityboy/hci.git
      path: retrofit
      ref: main
  source_gen: ^1.3.2
  tuple: ^2.0.2

dev_dependencies:
  lints: ^2.1.1
  source_gen_test: ^1.0.5
  test: ^1.21.4
