name: fwfh_cached_network_image
version: 0.7.0+5-hcifork.0
description: WidgetFactory extension to render IMG with cached_network_image plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.2.0"
  sdk: ">=2.13.0 <4.0.0"

dependencies:
  cached_network_image:
    git:
      url: https://github.com/zoocityboy/hci.git
      path: flutter_cached_network_image/cached_network_image
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: https://github.com/zoocityboy/hci.git
      path: flutter_cache_manager/flutter_cache_manager
      ref: main
  flutter_widget_from_html_core: #">=0.8.0 <0.11.0"
    git:
      url: https://github.com/zoocityboy/hci.git
      path: flutter_widget_from_html/packages/core
      ref: main

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core
  fwfh_text_style:
    path: ../fwfh_text_style

dev_dependencies:
  file: any
  flutter_test:
    sdk: flutter
  lint: any
  mocktail: ^0.3.0
